### PR TITLE
improve test coverage

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
For some reason, Jenkins has this in the log: `Caused by: java.io.FileNotFoundException: https://api.github.com/repos/snowdrop/spring-boot-cache-booster/pulls/7/commits` and that's why `rhoar-bot` didn't ask for testing the PR :-/

**Comment by geoand** [comment]
Weird :P

**Comment by Ladicek** [comment]
Ha, this worked! :-)

**Comment by geoand** [comment]
Thanks for this PR @Ladicek!

**Pull request merged**
