### PR TITLE
renamed caching service template and moved

### PR DESCRIPTION
**Pull request by rhoads-zach**
@geoand @metacosm let me know what you think

### CODE REVIEW

**Comment by Ladicek** [comment]
@rhoads-zach This is wrong, the `.openshiftio/service.cache.yaml` file needs to stay -- without it, Launcher wouldn't launch the JDG service and the booster wouldn't work. We need a _copy_ of that file in the root directory.

**Comment by metacosm** [comment]
@rhoads-zach what is the point of that change?

**Comment by Ladicek** [comment]
Launcher deletes the `.openshiftio` directories when creating the .zip / Git repo, and even if it didn't, finding the file in the root directory is much more user-friendly.

**Comment by rhoads-zach** [comment]
@Ladicek @metacosm amended the PR.

**Comment by metacosm** [comment]
Not a big fan of having to maintain two copies of the same file… :/ Not to mention that this is not consistent across boosters. ConfigMap does things differently for example (though the use case is slightly different, files are not put at the root of the booster). Generally speaking, I think we lack information about the booster structure, i.e. what is relevant to the actual use case and what is actually ceremony. Moreover, we don't really provide any technical details on the implementation, which I think is kind of weird considering the missions are supposed to show how to implement a given pattern for a given runtime.

**Comment by Ladicek** [comment]
As a matter of fact, there _is_ a config file in the root directory at least in one of the ConfigMap boosters :-)

**Comment by rhoads-zach** [comment]
@Ladicek @metacosm I am unclear where you all want to go from here.

Do i need to amend this PR with something else? Or does this need to sit until decisions are made?

**Comment by Ladicek** [comment]
I think this is good and should be merged. I kinda sorta understand @metacosm's reservations, but wouldn't block this PR on them.

**Comment by rhoads-zach** [comment]
@metacosm are you ok with merging?

**Comment by metacosm** [comment]
LGTM with the above reservations… What do you think, @geoand?

**Comment by Ladicek** [comment]
The only burden is that whenever we update the file (which is maintained by someone else, not us), we have to remember to update it on both places :-)

**Comment by geoand** [comment]
That's what I was referring to :)

**Comment by geoand** [comment]
@metacosm Should we go ahead and merge?

**Comment by metacosm** [comment]
+1 for the merge

**Comment by rhoads-zach** [comment]
thank you @metacosm @geoand @Ladicek

**Comment by geoand** [comment]
Thank you for the PR!

**Pull request merged**
