### PR TITLE
Bring UI in line with the other boosters

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@Ladicek Can you please take a look?

**Comment by geoand** [comment]
I shamelessly copied the UI (almost) verbatim from Wildfly Swarm :), I hope that's OK @michalszynkiewicz

**Comment by michalszynkiewicz** [comment]
@geoand yesterday I copied the vert.x page to our booster, now it looks like this: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-cache/blob/master/greeting-service/src/main/webapp/index.html

**Comment by geoand** [comment]
So is that the UI that is going to be common for all the caching boosters?

**Comment by metacosm** [comment]
Yet another example of lack of synch… :(

**Comment by geoand** [comment]
@michalszynkiewicz I see that the latest UI does not show the duration of the call as opposed to your previous UI.
So I'm a little confused on which UI I should copy :P

@Ladicek Can you shed some light please?

**Comment by Ladicek** [comment]
Well, I don't really know. I would have expected that the UI by @cescoffier would satisfy all the requirements, as @cescoffier is also the mission author, but if not... well at least we know who to  blame :-)

**Comment by geoand** [comment]
OK, I updated the PR with the latest UI from Swarm

**Comment by cescoffier** [comment]
Achtung! We need to sync with doc team here about the common text we will use. Mine can be read as a lorem ipsum.

**Comment by metacosm** [comment]
That was my understanding as well. But we will still blame you, @cescoffier! ;)

**Comment by geoand** [comment]
So @michalszynkiewicz are you going to revert? If so, I will update the PR with your previous UI

**Comment by metacosm** [comment]
I think @cescoffier's point is that the UI will still need to be updated once doc team has settled on proper wording. I think we can use the vert.x one as base for now.

**Comment by geoand** [comment]
OK, I guess I understood wrong :)

**Comment by Ladicek** [comment]
Yea I agree with @metacosm -- we'll probably want to do one more pass on the UI, but I feel it's important we share a single UI across all implementations.

**Comment by geoand** [comment]
Cool, I'll leave this PR open then so I can make the necessary changes when everything finalizes

**Comment by geoand** [comment]
I'd be happy to update / merge this ASAP :)

**Comment by cescoffier** [comment]
The Vert.x booster got the text updated and has reuse your (brilliant) duration idea.

**Comment by geoand** [comment]
@cescoffier I will proceed to copy your UI then :)

**Comment by geoand** [comment]
PR updated. 
I will go ahead and merge it when the tests complete

**Comment by Ladicek** [comment]
CC @michalszynkiewicz

**Comment by geoand** [comment]
retest this please

**Pull request merged**
